name: Build Android APK with Kivy (Python 3.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 确保有上传权限
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Buildozer and Kivy
        run: |
          pip install buildozer==1.2.0
          pip install kivy==2.2.1
          pip install pillow==10.0.1

      - name: Buildozer bootstrap
        run: buildozer android.bootstrap --requirements=python3,kivy

      - name: Build APK
        run: buildozer android.build
        env:
          ANDROID_API: 30

      - name: Archive APK (备用方案)
        if: success() || failure()  # 确保无论构建结果如何都执行
        run: |
          mkdir -p artifacts
          cp bin/*.apk artifacts/ || echo "No APK found"
          echo "ARTIFACT_PATH=$(pwd)/artifacts" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.2
        continue-on-error: true  # 允许上传失败
        with:
          name: apk
          path: bin/*.apk
