name: Build Android APK with Kivy (Python 3.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 确保有上传权限
      artifacts: write  # 明确工件上传权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Buildozer and Kivy
        run: |
          pip install buildozer==1.2.0
          pip install kivy==2.2.1 pillow==10.0.1

      - name: Buildozer bootstrap
        run: buildozer android.bootstrap --requirements=python3,kivy

      - name: Build APK
        run: buildozer android.build
        env:
          ANDROID_API: 30

      - name: Verify APK exists
        run: |
          if [ -f "bin/*.apk" ]; then
            echo "✅ APK found!"
            ls -la bin/
          else
            echo "❌ ERROR: No APK found in bin/ directory!"
            exit 1
          fi

      - name: Archive APK (备选方案)
        run: |
          mkdir -p artifacts
          cp bin/*.apk artifacts/ || echo "No APK found"
          echo "ARTIFACT_PATH=$(pwd)/artifacts" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        continue-on-error: true  # 允许上传失败
        with:
          name: apk
          path: bin/*.apk

      - name: Upload via GitHub CLI (备选方案)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading APK via GitHub CLI..."
          gh release upload --clobber "v$(date +%Y%m%d)" artifacts/*.apk || true
