name: Build Android APK with Kivy (Python 3.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout upload-artifact action
        uses: actions/checkout@v4
        with:
          repository: actions/upload-artifact
          ref: v3.1.2  # 指定版本
          path: .github/actions/upload-artifact  # 本地路径

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build APK
        run: |
          pip install buildozer==1.2.0 kivy==2.2.1 pillow==10.0.1
          buildozer android.bootstrap --requirements=python3,kivy
          buildozer android.build
        env:
          ANDROID_API: 30

      - name: Verify APK exists
        run: |
          if [ -f "bin/*.apk" ]; then
            echo "✅ APK found!"
            ls -la bin/
          else
            echo "❌ ERROR: No APK found!"
            exit 1
          fi

      - name: Upload APK artifact (本地引用)
        uses: ./.github/actions/upload-artifact  # 本地路径
        with:
          name: apk
          path: bin/*.apk

      - name: Upload via GitHub CLI (备选方案)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading APK via GitHub CLI..."
          gh release upload --clobber "v$(date +%Y%m%d)" bin/*.apk || true
