name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython

      - name: Setup Android SDK with License Acceptance
        uses: android-actions/setup-android@v2
        with:
          packages: |
            build-tools;30.0.3
            platforms;android-30
            platform-tools
          license-accept: true
          android-sdk-version: 30

      - name: Verify buildozer.spec exists and configure
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init -v
            sed -i 's/package.name = myapp/package.name = your_app_name/' buildozer.spec
            sed -i 's/requirements =.*/requirements = python3,kivy/' buildozer.spec
          fi
          # 显示配置文件内容用于调试
          cat buildozer.spec

      - name: Build APK
        run: |
          # 移除不兼容的 clean 命令
          buildozer -v android debug
          mkdir artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: artifacts/
