- name: Create GitHub Release
  if: success()
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    # 创建发布
    TAG_NAME="build-$(date +%Y%m%d%H%M%S)"
    curl -s -X POST \
      -H "Authorization: token $GITHUB_TOKEN" \
      -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" \
      -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"Build $(date +%Y-%m-%d %H:%M:%S)\",\"body\":\"Automated build\"}"
    
    # 获取发布 ID
    RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/$TAG_NAME" \
      | grep -o '"id": [0-9]*' | grep -o '[0-9]*')
    
    # 上传 APK
    if [ -f bin/*.apk ]; then
      APK_FILE=$(find bin -name '*.apk')
      APK_NAME=$(basename $APK_FILE)
      curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Content-Type: application/octet-stream" \
        "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$APK_NAME" \
        --data-binary "@$APK_FILE"
    fi
    
    echo "Release created: https://github.com/$GITHUB_REPOSITORY/releases/tag/$TAG_NAME"
