name: Build Android APK with Kivy (Python 3.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install buildozer==1.2.0 kivy==2.2.1 pillow==10.0.1

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build APK
        run: buildozer -v android debug
        env:
          ANDROID_API: 30
          ANDROID_NDK: 25c

      - name: Verify APK exists
        run: |
          if [ -f "bin/*.apk" ]; then
            echo "✅ APK found!"
            ls -la bin/
          else
            echo "❌ ERROR: No APK found!"
            exit 1
          fi

      - name: Archive APK (备选方案)
        run: |
          mkdir -p artifacts
          cp bin/*.apk artifacts/ || echo "No APK found"
          echo "ARTIFACT_PATH=$(pwd)/artifacts" >> $GITHUB_ENV

      - name: Upload via GitHub CLI (主要上传方法)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 创建临时 Release
          gh release create "v$(date +%Y%m%d)" --title "Build $(date +%Y%m%d)" --notes "Automated build"
          # 上传 APK
          gh release upload "v$(date +%Y%m%d)" artifacts/*.apk --clobber
