name: Build Kivy APK with AIDL Debugging

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          # 添加路径参数确保检出到正确目录
          path: ./repo

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # 移除自动缓存，使用自定义缓存逻辑
          # cache: 'pip'

      - name: Validate project files
        run: |
          echo "::group::Checking project files"
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          
          # 检查仓库目录是否存在
          if [ -d "./repo" ]; then
            echo "Repository checked out to ./repo"
            cd ./repo
            echo "Contents of repository:"
            ls -la
            
            # 检查 requirements.txt 是否存在
            if [ -f "requirements.txt" ]; then
              echo "requirements.txt found"
              cat requirements.txt
            else
              echo "::warning::requirements.txt not found in repository root"
              echo "Creating minimal requirements.txt for buildozer"
              cat > requirements.txt << EOF
buildozer
cython
kivy
pillow
EOF
              echo "Created minimal requirements.txt"
            fi
            
            # 检查 buildozer.spec 是否存在
            if [ -f "buildozer.spec" ]; then
              echo "buildozer.spec found"
            else
              echo "::warning::buildozer.spec not found in repository root"
            fi
          else
            echo "::error::Repository not checked out to ./repo"
            exit 1
          fi
          echo "::endgroup::"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            **/__pycache__
          # 使用当前时间戳作为缓存键，确保每次都能继续执行
          key: ${{ runner.os }}-pip-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          echo "::group::Installing dependencies"
          cd ./repo
          python -m pip install --upgrade pip
          python -m pip install buildozer cython
          echo "::endgroup::"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          packages: |
            build-tools;30.0.3
            platforms;android-30
            platform-tools
            tools
            ndk;25.2.9519653
          license-accept: true

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            $ANDROID_HOME
            $ANDROID_HOME/cmdline-tools
          key: ${{ runner.os }}-android-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-android-

      - name: Generate buildozer.spec (with AIDL support)
        run: |
          echo "::group::Generating buildozer.spec"
          cd ./repo
          echo "Creating default buildozer.spec dynamically"
          
          # 创建基本的 buildozer.spec 内容
          cat > buildozer.spec << 'EOF'
            [app]
            title = Your App Title
            package.name = your.app.name
            package.domain = com.yourdomain
            version = 1.0.0
            source.dir = .
            source.include_exts = py,png,jpg,kv,atlas,ttf,aidl
            requirements = python3,kivy,pillow
            android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,CAMERA
            android.api = 33
            android.minapi = 23
            android.sdk = 33
            android.ndk = 25c
            android.arch = armeabi-v7a
            orientation = portrait
            fullscreen = 0
            android.aidl_include_dirs = src/main/aidl
            android.logcat_filters = *:S python:D
            android.gradle_dependencies = com.android.support:support-v4:27.1.1
          EOF
          
          # 打印配置用于调试
          cat buildozer.spec
          echo "::endgroup::"

      - name: Validate Android SDK environment
        run: |
          echo "::group::Validating Android SDK environment"
          cd ./repo
          echo "=== ANDROID ENVIRONMENT CHECK ==="
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "SDK Tools Version:"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version
          echo "Build Tools Path:"
          ls -ld $ANDROID_HOME/build-tools/30.0.3
          echo "AIDL Tool Path:"
          ls -l $ANDROID_HOME/build-tools/30.0.3/aidl
          echo "::endgroup::"

      - name: List project files (for debugging)
        run: |
          echo "::group::Listing project files"
          cd ./repo
          echo "=== PROJECT FILE STRUCTURE ==="
          ls -laR .
          echo "=== AIDL FILES FOUND ==="
          find . -type f -name "*.aidl"
          echo "::endgroup::"

      - name: Accept SDK licenses (debug version)
        run: |
          echo "::group::Accepting SDK licenses"
          cd ./repo
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list
          echo "::endgroup::"

      - name: Test AIDL tool with minimal parameters
        run: |
          echo "::group::Testing AIDL compiler"
          cd ./repo
          echo "=== TESTING AIDL COMPILER ==="
          # 替换为你的实际 AIDL 文件路径（示例路径）
          AIDL_FILE_PATH="src/main/aidl/com/example/MyService.aidl"
          
          if [ -f "$AIDL_FILE_PATH" ]; then
            echo "Compiling AIDL file: $AIDL_FILE_PATH"
            # 基础编译命令（可根据需要添加参数）
            $ANDROID_HOME/build-tools/30.0.3/aidl \
              --out src/main/java \
              --header_out src/main/cpp \
              "$AIDL_FILE_PATH"
            echo "AIDL compilation successful"
          else
            echo "WARNING: AIDL file not found at $AIDL_FILE_PATH"
            echo "Creating sample AIDL file for testing"
            mkdir -p src/main/aidl/com/example
            cat > "$AIDL_FILE_PATH" << 'EOF'
              package com.example;
              interface MyService {
                void basicTypes(int anInt, long aLong, boolean aBoolean);
              }
            EOF
            echo "Sample AIDL file created"
          fi
          echo "::endgroup::"

      - name: Build APK (with debug logs)
        run: |
          echo "::group::Building APK"
          cd ./repo
          echo "=== STARTING APK BUILD ==="
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export BUILDOZER_DEBUG=1
          
          # 检查 buildozer 配置
          buildozer android debug --print_config_only
          
          # 构建 APK
          buildozer -v android debug || { 
            echo "::error::APK build failed"
            # 输出详细的错误信息
            cat bin/buildozer.log
            exit 1
          }
          
          # 检查 APK 是否生成
          if [ -f bin/*.apk ]; then
            echo "APK successfully built"
            mkdir -p artifacts
            cp bin/*.apk artifacts/
          else
            echo "::error::No APK found after build"
            exit 1
          fi
          echo "::endgroup::"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: ./repo/artifacts/
          retention-days: 7
