name: Build Kivy APK without JAXB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          path: ./repo

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Validate project files
        run: |
          echo "::group::Checking project files"
          cd ./repo
          if [ ! -f "buildozer.spec" ]; then
            echo "::error::buildozer.spec not found in repository root"
            exit 1
          fi
          echo "::endgroup::"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            **/__pycache__
          key: ${{ runner.os }}-pip-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          echo "::group::Installing dependencies"
          cd ./repo
          python -m pip install --upgrade pip
          python -m pip install buildozer cython
          echo "::endgroup::"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          components: |
            platforms;android-30
            platform-tools
            cmdline-tools;latest
            tools
            ndk;25.2.9519653
          accept-licenses: true

      - name: Force accept all Android SDK licenses
        run: |
          echo "::group::Force accepting all Android SDK licenses"
          mkdir -p $ANDROID_HOME/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1e9" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/intel-android-extra-license
          echo "8933bad161af4178b1185d1a37fbf41ea5269c5" > $ANDROID_HOME/licenses/android-sdk-license
          echo "::endgroup::"

      - name: Build APK
        run: |
          echo "::group::Building APK"
          cd ./repo
          buildozer -v android debug
          echo "::endgroup::"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./repo/bin/*.apk
