name: Build Android APK with Kivy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            git build-essential python3-dev \
            libffi-dev libssl-dev openjdk-11-jdk \
            zip unzip

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.2.0 kivy==2.2.1

      - name: Initialize Buildozer
        run: buildozer init

      - name: Configure buildozer.spec
        run: |
          sed -i 's/# android.ndk = .*/android.ndk = 26b/' buildozer.spec
          sed -i 's/# android.api = .*/android.api = 33/' buildozer.spec
          sed -i 's/# requirements = .*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/# android.accept_sdk_license = .*/android.accept_sdk_license = True/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug
          ls -la bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
          if-no-files-found: error
