name: Build Android APK with Kivy (Python 3.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install buildozer==1.2.0 kivy==2.2.1 pillow==10.0.1
          pip install Cython==0.29.32  # 显式安装 Cython
          python -m pip install --upgrade pip  # 升级 pip
          pip --version
          cython --version  # 验证 Cython 安装

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build APK
        run: buildozer -v android debug
        env:
          ANDROID_API: 30
          ANDROID_NDK: 25c
          PATH: ${{ github.workspace }}/.local/bin:${{ env.PATH }}  # 添加本地 bin 目录到 PATH

      - name: Verify APK exists
        run: |
          if [ -f "bin/*.apk" ]; then
            echo "✅ APK found!"
            ls -la bin/
          else
            echo "❌ ERROR: No APK found!"
            exit 1
          fi

      - name: Archive APK
        run: |
          mkdir -p artifacts
          cp bin/*.apk artifacts/ || echo "No APK found"
          echo "ARTIFACT_PATH=$(pwd)/artifacts" >> $GITHUB_ENV

      - name: Upload via GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$(date +%Y%m%d)" --title "Build $(date +%Y%m%d)" --notes "Automated build"
          gh release upload "v$(date +%Y%m%d)" artifacts/*.apk --clobber
