name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Setup Python 3.10
        uses: https://github.com/actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install buildozer cython

      - name: Install Android SDK (Manual)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip ant android-sdk android-sdk-platform-tools android-sdk-build-tools
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platforms;android-30" "tools"
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
          echo $ANDROID_HOME
          echo $PATH

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK
        uses: https://github.com/actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: artifacts/
