- name: Patch Python for Android
        run: |
          set -e  # 确保任何命令失败都会导致脚本退出
          
          # 克隆 Python for Android 仓库
          echo "Cloning Python for Android repository..."
          git clone https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
          
          # 可选：切换到特定版本以确保兼容性
          cd ~/.buildozer/android/platform/python-for-android
          git checkout master  # 或指定特定版本的标签
          
          # 查找 NDK 版本定义文件
          echo "Searching for NDK version definition..."
          find_result=$(find ~/.buildozer/android/platform/python-for-android -name "download.py" -o -name "ndk.py" -o -name "versions.py" -o -name "toolchain.py")
          
          if [ -z "$find_result" ]; then
            echo "❌ ERROR: Could not find NDK version definition files"
            exit 1
          else
            echo "✅ Found files:"
            echo "$find_result"
          fi
          
          # 修改文件
          echo "Patching toolchain.py..."
          sed -i 's/DEFAULT_NDK_VERSION = "25b"/DEFAULT_NDK_VERSION = "26b"/' \
            ~/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py
          
          # 验证修改
          echo "Verifying modification..."
          grep_result=$(grep -r "DEFAULT_NDK_VERSION" ~/.buildozer/android/platform/python-for-android)
          
          if [ -z "$grep_result" ]; then
            echo "❌ ERROR: Failed to verify modification"
            exit 1
          else
            echo "✅ Patched toolchain.py:"
            echo "$grep_result"
          fi
          
          # 检查目录权限
          echo "Checking directory permissions:"
          ls -la ~/.buildozer/android/platform/python-for-android
          
          # 验证 p4a 可执行文件
          echo "Checking p4a executable:"
          if [ -f ~/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py ]; then
            echo "✅ p4a toolchain.py found"
          else
            echo "❌ ERROR: p4a toolchain.py not found"
            exit 1
          fi
          
          # 额外检查：确保修改成功
          echo "Additional check: content of toolchain.py"
          grep "DEFAULT_NDK_VERSION" ~/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py
          
          echo "✅ Python for Android successfully patched!"
