name: Build Android APK with Kivy (Python 3.10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install buildozer==1.2.0 kivy==2.2.1 pillow==10.0.1

      - name: Initialize Buildozer
        run: buildozer init  # 创建 buildozer.spec 配置文件

      - name: Build APK
        run: buildozer -v android debug
        env:
          ANDROID_API: 30
          ANDROID_NDK: 25c  # 指定 NDK 版本

      - name: Verify APK exists
        run: |
          if [ -f "bin/*.apk" ]; then
            echo "✅ APK found!"
            ls -la bin/
          else
            echo "❌ ERROR: No APK found!"
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: apk
          path: bin/*.apk

      - name: Upload via GitHub CLI (备选方案)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload --clobber "v$(date +%Y%m%d)" bin/*.apk || true
