name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK (Manual)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip ant android-sdk
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platforms;android-30" "tools"
          echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: artifacts/
