name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          packages: |
            build-tools;30.0.3
            platforms;android-30
            platform-tools
          license-accept: true

      - name: Verify buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec not found. Creating default..."
            buildozer init
          else
            echo "buildozer.spec found. Proceeding..."
          fi
          cat buildozer.spec  # 打印配置文件内容，便于调试

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: artifacts/
