name: Build Kivy APK with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest  # 官方预配置的 Buildozer Docker 镜像
      options: --privileged  # 授予必要权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate buildozer.spec (if missing)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init -v
            sed -i 's/package.name = myapp/package.name = your_app_name/' buildozer.spec
            sed -i 's/requirements =.*/requirements = python3,kivy/' buildozer.spec
          fi
          cat buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug
          mkdir -p artifacts
          cp bin/*.apk artifacts/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: artifacts/
